create table jbpm_correlationpropertyinfo (id bigint not null, name varchar(255), value varchar(255), optlock integer, correlationkey_id bigint, primary key (id));
create table jbpm_processinstanceeventinfo (id bigint not null, eventtype varchar(255), processinstanceid bigint, optlock integer, primary key (id));
create table jbpm_processinstanceinfo (processinstanceid bigint not null, lastmodificationdate timestamp, lastreaddate timestamp, processid varchar(255), processinstancebytearray bytea, startdate timestamp, state integer, optlock integer, primary key (processinstanceid));
create table jbpm_workiteminfo (workitemid bigint not null, creationdate timestamp, name varchar(255), processinstanceid bigint, state bigint, optlock integer, workitembytearray bytea, primary key (workitemid));
create table jbpm_sessioninfo (id integer not null, lastmodificationdate timestamp, rulesbytearray bytea, startdate timestamp, optlock integer, primary key (id));
create table jbpm_correlationkeyinfo (id bigint not null, name varchar(255), processinstanceid bigint, optlock integer, primary key (id));
create table jbpm_process_event (id bigint not null, event varchar(255), process_instance bigint, "session" integer, primary key (id));
create index jbpm_pe_session on jbpm_process_event ("session");
create index index_jbpm_process_event_event on jbpm_process_event (event);
create index jbpm_pe_pinstance on jbpm_process_event (process_instance);
create table jbpm_eventtypes (fk_proc_instance_id bigint, eventtypes varchar(255));
alter table jbpm_correlationpropertyinfo add constraint fk_jbpm_correlationpropertyinfo_correlationkey_id foreign key (correlationkey_id) references jbpm_correlationkeyinfo (id);
alter table jbpm_eventtypes add constraint fk_jbpm_eventtypes_fk_proc_instance_id foreign key (fk_proc_instance_id) references jbpm_processinstanceinfo (processinstanceid);
create sequence jbpm_correlation_key_id_seq increment by 50 start with 50;
create sequence jbpm_pinstance_info_id_seq increment by 50 start with 50;
create sequence jbpm_proc_inst_event_id_seq start with 1;
create sequence jbpm_workiteminfo_id_seq increment by 50 start with 50;
create sequence jbpm_sessioninfo_id_seq increment by 50 start with 50;
create sequence jbpm_correlation_prop_id_seq increment by 50 start with 50;